### ISSUE TITLE
"File download ran into problems. Please try to download again."

### ISSUE THREAD

**Issue by dylanmr** [MaayanLab/archs4#2] opened 2018-08-09 07:52 UTC
Hi and thank you for this great resource! I have been trying to download the hdf5 files using the auto-generated rscripts, but I continue to run into this error regardless of the dataset I try to download. 

"File download ran into problems. Please try to download again."

Do you have any recommendations on how to fix this?

Best,
Dylan

**Comment by lachmann12** [comment] 2018-08-16 21:29
For some reason that we can't reproduce the file can get corrupted during the download process when using the R-script. We now support direct download next to the R-script link as long as it is fewer than 2000 samples. 

If the R-script fails we would recommend downloading the file manually and skipping the download section of the script. 

Sorry for the inconvenience.

Best,
Alex

**Comment by lachmann12** [comment] 2018-08-16 21:30
The files are located at:

https://amp.pharm.mssm.edu/archs4/download.html

**Comment by lachmann12** [comment] 2018-08-16 22:35
There was also an issue with the new checksums not loading properly. This should be fixed now.

**Closed** 2018-08-17 14:48 UTC
